export const FETCH_LESSONS = 'FETCH_LESSONS'
export const SET_CURRENT_LESSON = 'SET_CURRENT_LESSON'
export const DELETE_LESSON = 'DELETE_LESSON'
export const SET_CURRENT_TASK = 'SET_CURRENT_TASK'
export const UPDATE_LESSON_TO_INSERT_HEADER = 'UPDATE_LESSON_TO_INSERT'
export const UPDATE_LESSON_TO_INSERT_FLASHCARDS = 'UPDATE_LESSON_TO_FLASHCARDS'
export const UPDATE_LESSON_TO_INSERT_LISTEN = 'UPDATE_LESSON_TO_INSERT_LISTEN'

